### ISSUE TITLE
Monitoring software sending tons of status emails

### ISSUE THREAD

**Issue by rstudley** [RTICWDT/evaluation-engine-website#11]
I had thought this was part of the "unable to send emails" issue ( #4 ), but apparently it's a separate issue. According to Alex:

We still have the problem related to some monitoring software (that I did not install and I know nothing about) trying to send tons of status emails. I’m not sure what to do about this problem at all.

**Comment by alexsmithRTI** [comment]
Neither of the two folks who were receiving the monitoring emails have asked that it be fixed.
