### ISSUE TITLE
Email delay

### ISSUE THREAD

**Issue by rstudley** [RTICWDT/evaluation-engine-website#12]
At about 1am last night, I received this notice (below) about job #255 (JobGUID: f9c62136-a4e9-4de5-a512-7a5b16402267) completing. But the job actually completed much earlier (sometime between 9:30 and 4pm). Please investigate to see if it's a quick fix. Otherwise, we might want to wait to see if the problem recurs before you spend much time on it.

-----Original Message-----
From: info@evaluationengine.org [mailto:info@evaluationengine.org] 
Sent: Thursday, March 02, 2017 1:20 AM
To: Studley, Roger <rstudley@rti.org>
Subject: Evaluation Engine - Report Status

The report you request has been completed.  

Please visit https://reviewevaluationengine.org/staging/Analysis/Step4/255 to view your report.

**Comment by alexsmithRTI** [comment]
This was probably related to the large queue of emails that got sent after the email service was restored. Closing for now, but we can reopen if it occurs again.
