### ISSUE TITLE
Warning about insecure connection

### ISSUE THREAD

**Issue by rstudley** [RTICWDT/evaluation-engine-website#13]
Alex, when signing on to reviewevaluationenging.org (either staging or production), I see the following warning when I click in the box for email address: "This connection is not secure. Logins entered here could be compromised." (See image.) I'm using Firefox 50.0.1 on Windows 7.

This will not be reassuring to potential clients. Can we fix it? Maybe wait and see if it still happens after the migration?

![image](https://cloud.githubusercontent.com/assets/22551862/24218718/8ba459b4-0f01-11e7-8f3c-3f4cba50c53a.png)

**Comment by alexsmithRTI** [comment]
This is fixed.
