### ISSUE TITLE
server error on student ID file upload

### ISSUE THREAD

**Issue by benthestatistician** [RTICWDT/evaluation-engine-website#2]
Initiating a new study on the staging instance, on attempting to upload a CSV file of student IDs at Step 1B I get the following server error:

> Server Error in '/staging' Application.

> Access to the path 'C:\inetpub\wwwroot\EvalEngine_staging\App_Data\uploads\919bf363-8cd3-40cd-b37b-22d415640904' is denied.

> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

> Exception Details: System.UnauthorizedAccessException: Access to the path 'C:\inetpub\wwwroot\EvalEngine_staging\App_Data\uploads\919bf363-8cd3-40cd-b37b-22d415640904' is denied. 

> ASP.NET is not authorized to access the requested resource. Consider granting access rights to the resource to the ASP.NET request identity. ASP.NET has a base process identity (typically {MACHINE}\ASPNET on IIS 5 or Network Service on IIS 6 and IIS 7, and the configured application pool identity on IIS 7.5) that is used if the application is not impersonating. If the application is impersonating via <identity impersonate="true"/>, the identity will be the anonymous user (typically IUSR_MACHINENAME) or the authenticated request user. 

And so forth; here's [a PDF of the page that comes up](https://github.com/RTICWDT/evaluation-engine-website/files/629534/servererrorI2.pdf), including the stack trace. 

The problem appears not to arise if instead of uploading a CSV file of student IDs I just paste the IDs into the provided dialog box.

My setup: Chrome 54.0.2840.98 (64-bit) on OS X 10.11.6 .

**Comment by rstudley** [comment]
@alexsmithRTI, is this the issue (#2, error on file upload) that has now been resolved?

**Comment by alexsmithRTI** [comment]
Yes, this has been fixed. The related issue (uploading IDs and a file) is separate.
