### ISSUE TITLE
Adjust navigation & buttons on Step2c (Adv Options) page

### ISSUE THREAD

**Issue by rstudley** [RTICWDT/evaluation-engine-website#5]
@alexsmithRTI : On the Step2c page, please (i) change the button text from "Save & Continue" to just "Save" and (ii) when a user hits either "Save" or "Back", use an anchor tag to direct them back to the _bottom_ of the Step2b page.

**Comment by rstudley** [comment]
(This is for the staging instance.)

**Comment by alexsmithRTI** [comment]
This is fixed on staging and development.
