### ISSUE TITLE
Unable to send emails from web1.matchstick.evaluationengine.org

### ISSUE THREAD

**Issue by rstudley** [RTICWDT/evaluation-engine-website#6]
This is not a new issue, I'm just tracking it here for completeness. @alexsmithRTI is currently pursuing this with David Nolan in ITS. The ITS ticket, initiated 16jan2017 is RTI1470632 = Need to update routing between extmail.rti.org and web1.matchstick.evaluationengine.org. From Alex's 11/29/2016 email to Jose:

I’m not sure when this started happening, but I just noticed it. Normal password reset emails won’t be sent. I noticed this issue while trying to diagnose another issue with the site.

I had a look at some of the bad emails (in C:\inetpub\mailroot\Badmail\) and see that there are a bunch of emails in the Queue (all of the emails I’ve been trying to send) and some in Badmail.

I see that the messages in badmail are supposed to be sent to sotorn@rti.org and bblater@rti.org, I’m assuming Sotorn Muangmanee and Brian Blater, but cannot connect to the mail server. I’m not sure if this has anything to do with the emails not working, but it seems like these are summaries of bad ssh requests, and other PDF data from the web server. Not sure why these emails are being sent and why we didn’t know about this. 

What I need to figure out is why all of our emails are queued rather than being sent. 

I’ve attached the most recent 3 bad emails, if that helps. Should I contact anyone else in ITS? I’ve worked with Shawn Reese and James T. Morrison on this before, so they might have an idea of what’s wrong. As it stands right now, I can’t fix what’s broken on the site and nobody would be able to send an email or know when a report has finished running.
[badmail.zip](https://github.com/RTICWDT/evaluation-engine-website/files/740770/badmail.zip)

**Comment by alexsmithRTI** [comment]
This issue has been resolved.
