### ISSUE TITLE
Fix weird behavior when IDs are BOTH uploaded AND manually entered

### ISSUE THREAD

**Issue by rstudley** [RTICWDT/evaluation-engine-website#7]
@alexsmithRTI : I accidentally _both_ uploaded a file of IDs _and_ I had some gibberish in the field for entering IDs by hand. When I did that, I got the following error: Please upload a file or paste information into the box.

But I had included a file for upload. The problem was that I had something in BOTH the “upload file” and “enter IDs” fields, and it took a while to figure out the problem. The existing error message is perfect for when there is NEITHER a file nor IDs. But can you add a separate message for the case of a user including both a file and IDs?

This was on the **production** instance, but it probably applies to **staging** and **development** as well. I have included a screen shot so that you can see what happened.

![image](https://cloud.githubusercontent.com/assets/22551862/22446951/467c34da-e704-11e6-8d4f-10c3bf0bc583.png)

**Comment by alexsmithRTI** [comment]
This is fixed on staging and development.
